<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore [
        <!ELEMENT bookstore (book+)>
        <!ELEMENT book (title, author, price)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ENTITY footer "wweellcome">
        <!ATTLIST book category CDATA #REQUIRED>
        ]>
<bookstore>
    <book category="fiction">
        <title>Harry Potter and the Philosopher's Stone</title>
        <author>J.K. Rowling</author>
        <price>20.00</price>
			  <footer>&footer;</footer>
    </book>
    <book category="fiction">
        <title>The Great Gatsby</title>
        <author>F. Scott Fitzgerald</author>
        <price>15.00</price>
    </book>
    <book category="nonfiction">
        <title>Sapiens: A Brief History of Humankind</title>
        <author>Yuval Noah Harari</author>
        <price>25.00</price>
    </book>
</bookstore>
